### ISSUE TITLE
Small values have no bars

### ISSUE THREAD

**Issue by pkerpedjiev** [Caleydo/lineupjs#167]
Example input file:

https://drive.google.com/open?id=0B2amcfXKOyc3YVd5ejV5Z1pOVUU

Cells with small values look the same as NaN cells (i.e. no value bars):

![image](https://cloud.githubusercontent.com/assets/2143629/20267894/c3d2701c-aa4a-11e6-8f0b-ba0435db81c9.png)

**Comment by sgratzl** [comment]
isn't that the basic idea? that small values have small bars. It if is the minimal value = no bar

**Comment by mstreit** [comment]
Yes, it is, but we should think about a way to let a user visually differentiate between NaN and small values (that have no bar because of the big values that determine the scale).

**Comment by pkerpedjiev** [comment]
That's an interesting question. In this case I would think that the NaN is
the "smallest" value.

What if the smallest value just has a width 1 line and the others are
scaled from there?

**Comment by mstreit** [comment]
As a user I would find it confusing if NaN would be treated as the smallest value. How about rendering a small x to indicate that this value is missing?

**Comment by zichner** [comment]
I think the minimal value should still have a (very thin) bar, especially since "minimal" does not necessarily mean that the value is 0.
Additionally, one could render some text for all cells that are either empty or contain some non numeric values (e.g., "NA", "NaN", ...). The rendered text could either be an "x" as suggested by @mstreit or it could be the actual content (i.e., "NaN", etc).

**Comment by mstreit** [comment]
I prefer the second solution, i.e., to explicitly mark non-numeric and missing values.

**Comment by mstreit** [comment]
If we use a false color it should not be very salient.

**Comment by sgratzl** [comment]
there is a now an explicit missing value encoding
