### ISSUE TITLE
missing values not detected in filter panel for categorical attributes

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#358]
Release number or git hash: Ordino KUK local
Web browser version and OS: chrome

Steps to reproduce
- load grading in KUK dataset

Observed behavior
- filter panel shows '0 missing values' although there are values missing

Any unexpected output or action (or lack of expected output or action)
- number of missing values in filter panel should be correct.

![image](https://user-images.githubusercontent.com/4129755/31426753-fafddc88-ae64-11e7-83dd-528488293cc3.png)

**Comment by sgratzl** [comment]
please stick to the issue template:

* Release number or git hash: 
* Web browser version and OS: 

### Steps to reproduce

1. 
2. 

### Observed behavior
* Any unexpected output or action (or lack of expected output or action)
* Web browser console errors (including tracebacks)
* Server errors (relevant messages and tracebacks)
* Static or animated images showing the UI behavior

### Expected behavior
*

**Comment by mstreit** [comment]
updated

**Comment by sgratzl** [comment]
part of https://github.com/Caleydo/lineupjs/commit/5e4c01c0306fe6145e9bfea9f2da6d1554fcdd44#diff-5e2dfdd4ad35e2e585fdf16a52bc5445R89
