### ISSUE TITLE
Fix drag'n'drop of columns in side panel

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#444]
* Release number or git hash: current
* Web browser version and OS: Chrome 63.0.3239.40

### Steps to reproduce

1. Drag a column header in the side panel
2. Try to drop it above or below another column

![broken-dnd-sidepanel](https://user-images.githubusercontent.com/5851088/32732507-16ddec08-c88d-11e7-91d5-a23465e987c7.gif)

### Observed behavior
* No drop area is shown
* Dropping it will not change the order

### Expected behavior
* Show drop area and change the order

**Comment by thinkh** [comment]
@sgratzl I couldn't figure out if there is an element or event missing. Please have a look.

**Comment by sgratzl** [comment]
it is native drag-and-drop There are no events. Does the drop area = handle elements exists?

**Comment by thinkh** [comment]
The handle was there, but had no style. I fixed it with the last commit.

**Comment by mstreit** [comment]
After merging the latest changes, the drag and drop looks nice but it still flickering in Chrome. @thinkh can you confirm this?

**Comment by thinkh** [comment]
Yes, I can confirm the flickering behavior. The commit https://github.com/Caleydo/lineupjs/pull/450/commits/8e9ca8cf56c0eed7d0298759dc7bd6ca63995ceb doesn't help. I tested it a bit further, and it seems that the check for the drop check is not working 100% correct. But I couldn't nail it to something specific.

**Comment by thinkh** [comment]
I observed that the mouse cursor is changing constantly between the forbidden sign and the drop icon. But only on some elements and/or regions.

**Comment by sgratzl** [comment]
I think the following happens. The issue is a combination of event bubbling + disabling all children
1. enter a child of the drop node -> bubbles up -> .drag-over
2. .drag-over style applies => child doesn't get any pointer-events
3. leave the child again -> bubbles up -> remove .drag-over
4. .drag-over style is gone -> go to step 1

doesn't always happen if the first element isn't a child but the node itself. Then
1. enter at node -> .drag-over
2. disable children
3. regular drop waiting

**Comment by thinkh** [comment]
Nice catch! 👍
