### ISSUE TITLE
better label support for narrow columns

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#522]
* Release number or git hash: dev

in case of very narrow columns the column label cannot be read at all. One option is to reimplement a rotated label feature. Tho, it has the big disadvantage that the whole header will get really huge. 

other ideas for a non-interactive solution?

**Comment by thinkh** [comment]
A quite simple fix is to reduce the [padding-left](https://github.com/Caleydo/lineupjs/blob/develop/src/styles/engine/_header.scss#L50) the label for narrow columns. I posted some links how to react on the width in https://github.com/Caleydo/lineupjs/issues/341. 

Another, but not necessarily the better option, is to cut out the middle, i.e. instead of `Ppl  know...` you can write `Ppl ... 2015)`. But this also requires quite a column width.

I also played around with the [original LineUp Demo](https://lineup.caleydoapp.org/) and I think that you can still use the diagonal approach.
At the moment the labels are placed diagonal when the column with is < 150px then the header is shifted down by 50px.

![image](https://user-images.githubusercontent.com/5851088/36530567-b69d0814-17bb-11e8-9ee7-0aad9354b9bb.png)

In my opinion the behavior can be applied at < 75px then the header can be shifted down by 30px. 

![image](https://user-images.githubusercontent.com/5851088/36530699-173ae92a-17bc-11e8-952d-758315586c93.png)

Another option would be to use a steeper angle instead of the 20deg.

**Comment by sgratzl** [comment]
my use case is when the column width is reduced to a heatmap only, i.e. around 20 px.

**Comment by thinkh** [comment]
Done. The option can be activated in the LineUp config (see [config.ts](https://github.com/Caleydo/lineupjs/blob/72c5298dfd3bc7413df27e3d48fa0c1480845bef/src/config.ts)).
