### ISSUE TITLE
Text of the the group name column shifted

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#555]
In the overview mode the name of the un-aggregated group is shifted and overlaps with the group/aggregetion indicator:
![image](https://user-images.githubusercontent.com/8986080/43261523-3b846280-90dd-11e8-909a-cb883bc9f561.png)

**Comment by thinkh** [comment]
I think there is a `position:relative` for `[data-meta="first"] [data-renderer="group"]` missing. 

![grafik](https://user-images.githubusercontent.com/5851088/43270009-5e5fbe3c-90f4-11e8-98fa-749ecd88adf7.png)

However, the left border looks still distorted like in your screenshot and can only be fixed in the canvas drawing.

![grafik](https://user-images.githubusercontent.com/5851088/43270093-8a0299ec-90f4-11e8-9781-dc52f08dd86b.png)

**Comment by thinkh** [comment]
Moved to https://github.com/datavisyn/lineupjs/issues/50.
